### ISSUE TITLE
链接：有XSS可能性

### ISSUE THREAD

**Issue by nocrizwang** [luogu-dev/markdown-palettes#10]
链接有XSS可能性
[xss](data:text/html;base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4K)

**Comment by nocrizwang** [comment]
`[xss](data:text/html;base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4K)`
举例

**Comment by dark-flames** [comment]
请参考[marked](https://github.com/markedjs/marked)下的[pr#844](https://github.com/markedjs/marked/pull/844)
