### ISSUE TITLE
HTML support

### ISSUE THREAD

**Issue by hi60year** [luogu-dev/markdown-palettes#11]
I'm a Luogu Online Judge user. When I edit an answer, I founded that when I use html codes, I can see the correct format on the browsing page. But after I submit it, I found my answer has been turned down. The reason is "Luogu doesn't support HTML, please delete the code and submit again."
I hope you can develop the feature that can support HTML.

**Comment by moesoha** [comment]
@hi60year Obviously, we denied raw HTML codes at back-end for security reason. This is NOT the issue of THIS project.

**Comment by hi60year** [comment]
@moesoha Thank you. But can you make browsing page not to display the format changed by HTML?

**Comment by laosb** [comment]
@hi60year We are not planning to support raw html. Your content will be eexmined by backend services, and it of course escape all raw html. So this is actually not really related to this repository. However, In our effort of engineering the new generation of luogu, the markdown content will be rendered client side, so this won't be a issue any more.

**Comment by hi60year** [comment]
@laosb Thank you.
