### ISSUE TITLE
What's the LICENSE of this project?

### ISSUE THREAD

**Issue by Xeonacid** [luogu-dev/markdown-palettes#22]

**Comment by dark-flames** [comment]
We use The MIT  License，it has been declared in `package.json`

**Comment by Xeonacid** [comment]
Thx, I think it's better to make a `LICENSE` file and/or declare it in `README.md`

**Comment by ghost** [comment]
I'll add `LICENSE` file in next pr.

**Comment by Xeonacid** [comment]
@TitanSnow Great, thanks!

**Comment by ghost** [comment]
Fixed in [31ca0d](https://github.com/TitanSnow/markdown-palettes/commit/31ca0d2e6466bca5ddb686a3be5b61cd59141603)
