### ISSUE TITLE
当文章比较长的时候，写一个字就卡一下

### ISSUE THREAD

**Issue by Planet6174** [luogu-dev/markdown-palettes#27]
我之前写一篇长文时就遇到过，当时以为是我的电脑太破烂（机房渣机）。结果后来有两三位写长文时也遇到这种情况。

**Comment by dark-flames** [comment]
已知bug，过一段时间会修复

**Comment by henla** [comment]
呵呵

**Comment by ghost** [comment]
I'm moving parsing process into Web Worker and I'm writing a remark reimplement in rust to make it faster. It takes time, though. My goal is to make Markdown*Palettes the fastest markdown editor. So no complaint at present please.
