### ISSUE TITLE
A proposition about the version of JavaScript

### ISSUE THREAD

**Issue by Link14349** [luogu-dev/markdown-palettes#28]
In your project, the version of JavaScript is _ES6_, but on the market, not all browsers support _ES6_ standards, and it is recommended that _ES6_ code be converted to _ES5_ code via command line tools.

**Comment by laosb** [comment]
@qianduanXIAOHAOZI According to the [browserlist](https://github.com/luogu-dev/markdown-palettes/blob/master/package.json#L45), all targeted browsers are ES6 ready. If you want a ES5 build, you can simply change the browser list and compile at your own.

**Comment by lin-toto** [comment]
@qianduanXIAOHAOZI According to the browserlist, all targeted browsers are ES6 ready. If you want a ES5 build, you can simply change the browser list and compile at your own.

**Comment by himself65** [comment]
@qianduanXIAOHAOZI According to the browserlist, all targeted browsers are ES6 ready. If you want a ES5 build, you can simply change the browser list and compile at your own.

**Comment by moesoha** [comment]
@qianduanXIAOHAOZI 根据 browserlist，所有目标浏览器都已经滋磁 ES6 了。如果你想要一个 ES5 的版本，你可以对 browserlist 进行修改然后自己编译。
