### ISSUE TITLE
代码块的错误

### ISSUE THREAD

**Issue by e3c8f1a924** [luogu-dev/markdown-palettes#36]
```
* a
'''
b

c
'''
```
将上面的'替换成`，再放到洛谷的Markdown编辑器中，会有错误产生，且实际显示的与预览的不一样。  

这个问题以前被提到过，但并未解决。

**Comment by e3c8f1a924** [comment]
见[https://www.luogu.org/paste/7sk8fdjn ](https://www.luogu.org/paste/7sk8fdjn)。

**Comment by moesoha** [comment]
这不是编辑器的锅，而是你的语法不规范。

` ``` ` 和上一行之间应当有一个空行，如

    * a
    

    ```
    b
    
    c
    ```

**Comment by e3c8f1a924** [comment]
@moesoha 但是其他编辑器不会有这样的问题。

**Comment by e3c8f1a924** [comment]
而且预览与实际显示不同。

**Comment by moesoha** [comment]
洛谷的渲染引擎和本项目所使用的渲染引擎并不相同，其中洛谷的渲染引擎在空行的处理上更为宽松。

Markdown 的方言有很多种，Markdown 编辑器和渲染引擎也有很多种，行为上不一致也是正常的。

**Comment by moesoha** [comment]
Do we need to add label like `compatibility` or `bug` to this issue? @dark-flames

**Comment by himself65** [comment]
可能是线上版本不对，在本地测试时候没有问题

![image](https://user-images.githubusercontent.com/14026360/51797138-58372500-2239-11e9-87f3-19cfe9a4e5eb.png)
