### ISSUE TITLE
引用不可使用

### ISSUE THREAD

**Issue by typist-coder** [luogu-dev/markdown-palettes#37]
目前在编辑器中**引用**语法不会有效果，与普通句子没有区别。

望解决

P.S.我在洛谷博客中使用，主题是Holakit，不知是博客、编辑器、主题哪个出了问题

**Comment by moesoha** [comment]
@xxxxx-qin 感谢反馈。这个应该是渲染引擎没有考虑这个规则，我们稍后会检查该问题。

**Comment by moesoha** [comment]
This is not a problem of this project. Close plz. @dark-flames

**Comment by dark-flames** [comment]
Fixed
