### ISSUE TITLE
“插入代码”的语言机制

### ISSUE THREAD

**Issue by rqy2002** [luogu-dev/markdown-palettes#4]
建议“插入代码”时可选择语言类型（下拉框什么的），而不是自己输入语言类型。
不然的话好多人会写 `c++` 而不是`cpp`
然后就会
![image](https://user-images.githubusercontent.com/22741844/35205300-08afb706-ff6f-11e7-8055-07db23f51cc7.png)

**Comment by lin-toto** [comment]
已加入
