### ISSUE TITLE
请教一个问题 I want to ask a question.

### ISSUE THREAD

**Issue by littlefrogfromthenorth** [luogu-dev/markdown-palettes#41]
这个项目的结构我看了代码之后大概了解了，我想在我自己的项目中使用它。但是我的项目中需要这个编辑器支持html标签，请问这个过滤html代码的地方在哪里呢？

I want to use markdown-palettes in my own projects,But please tell me where is used to escape HTML ?

**Comment by moesoha** [comment]
@littlefrogsite 编辑器不会对 HTML 进行转义，你应该检查自己的项目有没有写错

**Comment by littlefrogfromthenorth** [comment]
![image](https://user-images.githubusercontent.com/49180735/78621148-7fb16500-78b4-11ea-974f-2dde6e646617.png)

这里是什么意思呢

**Comment by littlefrogfromthenorth** [comment]
哦哦哦，傻逼了傻逼了，这是markdown-it自带的安全功能，弄混了

**Comment by littlefrogfromthenorth** [comment]
不用了
