### ISSUE TITLE
多行公式问题

### ISSUE THREAD

**Issue by GekkaSaori** [luogu-dev/markdown-palettes#6]
```c++
#include<cstdio>
using namespace std; 
int main() 
{
    printf("hello, world");
    return 0; 
}
```
Name|Academy|score 
:-:|:-:|:-:
Harry Potter|Gryffindor|90 
Hermione Granger|Gryffindor|100
Draco Malfoy|Slytherin|90

上面是使用Markdown语法手动插入的4\*3表格.

|  |  |  |
| ------------ | ------------ | ------------ |
|  |  |  |
|  |  |  |
|  |  |  |

上面是使用编辑器插入的4\*3表格.

单行公式：

$\prod_{d=1}^n\text{Fib}[d]^{\sum_{i=1}^{\min\left(\left\lfloor\frac nk\right\rfloor,\left\lfloor\frac mk\right\rfloor\right)}\mu(k)\sum_{i=1}^{\left\lfloor\frac nk\right\rfloor}\sum_{k|i}1\sum_{j=1}^{\left\lfloor\frac mk\right\rfloor}\sum_{k|j}1}$

多行公式测试：

$$
f[i][j]=\left{\begin{matrix} f[i-1][j-1]+1 & , X[i]=Y[j] \ \max(f[i][j-1],f[i-1][j]) & , X[i]\neq Y[j] \end{matrix}\right.
$$

多行公式似乎仍然不受支持。测试代码：
```TeX
$$
f[i][j]=\left\{\begin{matrix}
        f[i-1][j-1]+1             & , X[i]=Y[j]     \\
        \max(f[i][j-1],f[i-1][j]) & , X[i]\neq Y[j]
    \end{matrix}\right.
$$
% 以上代码都吞掉了一个公式定界符。
```
矩阵环境等公式环境目前仍不被支持。希望能加入公式使用完整\LaTeX语法功能，比如支持公式环境等等。

粗略的测试了一下，目前对多行公式的支持仍然较差。

另外代码环境似乎有些问题。自动识别代码与手动定界代码有些冲突。

**Comment by GekkaSaori** [comment]
请在洛谷测试以上代码。

**Comment by lin-toto** [comment]
以上全都是luogu历史遗留问题，与编辑器无关。
