### ISSUE TITLE
Turn off Markdown syntax highlight and add LaTeX syntax highlight in LaTeX code

### ISSUE THREAD

**Issue by ghost** [luogu-dev/markdown-palettes#8]
The LaTeX code in `$..$` and `$$..$$` is wrongly highlighted in Markdown syntax:

![temp](https://user-images.githubusercontent.com/19969470/35441607-0c2b4c8a-029c-11e8-9af0-2c196be59fbf.png)

**Comment by lin-toto** [comment]
This issue is difficult to fix since it's related to CodeMirror rendering behaviors. If you have some suggestions on this please comment

**Comment by ghost** [comment]
Generally the way might be to [write a custom CodeMirror mode](http://codemirror.net/doc/manual.html#modeapi).

**Comment by lin-toto** [comment]
@dark-flames
